name: CI

on: [push]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install dependencies
      run: yarn
  
  test:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
    - name: Unit tests
      run: yarn test
  
  build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
    - name: Build
      run: yarn build
      
